# Generated by Django 2.2.7 on 2019-11-25 20:17

import apps.core.files_paths
import colorful.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musorka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'empty'), (2, 'full')], default=1)),
                ('volume', models.PositiveIntegerField()),
                ('counter', models.PositiveIntegerField(default=0)),
                ('color', colorful.fields.RGBColorField()),
                ('image', models.ImageField(blank=True, max_length=255, upload_to=apps.core.files_paths.musorka_image_path)),
                ('matherial', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('user', models.ManyToManyField(related_name='musorka', related_query_name='musorka', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
