# Generated by Django 2.2.7 on 2019-11-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musorka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusorkaHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_time', models.DateTimeField()),
                ('full_time', models.DateTimeField()),
                ('musorka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='musorka.Musorka')),
            ],
        ),
    ]
