# Generated by Django 2.2.7 on 2019-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musorka', '0002_musorkahistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musorkahistorymodel',
            name='empty_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='musorkahistorymodel',
            name='full_time',
            field=models.DateTimeField(null=True),
        ),
    ]
