# Generated by Django 2.2.7 on 2019-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musorka', '0003_auto_20191125_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='musorkahistorymodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'empty'), (2, 'full')], default=1),
        ),
    ]
