# Generated by Django 2.2.7 on 2019-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musorka', '0004_musorkahistorymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='musorkahistorymodel',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
